"""
Builds a styled PDF of a document's AI-generated summary, for the
"Export" button in SummaryPanel.jsx.

Colors below approximate the app's existing Tailwind palette (teal /
amber / ink / slate / parchment / rule) by eye from the screenshots —
if you have the exact hex values from tailwind.config.js, swap them in
for a pixel-accurate match.

Note on typography: reportlab ships only the base 14 PDF fonts
(Helvetica, Times, Courier families) without embedding a TTF, so this
uses Helvetica-Bold for headings rather than the app's actual display
font. If you want the real font (e.g. a serif display face) embedded,
give me the font file/name and I'll register it with pdfmetrics.
"""
import io
from datetime import datetime, timezone

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)

# --- palette (approximate — see module docstring) ---------------------------
INK = colors.Color(0.11, 0.10, 0.09)          # near-black warm gray, body text
SLATE = colors.Color(0.36, 0.34, 0.31)         # secondary/meta text
AMBER = colors.Color(0.68, 0.36, 0.06)         # section label accent
TEAL = colors.Color(0.06, 0.35, 0.33)          # header band / primary accent
TEAL_DARK = colors.Color(0.04, 0.27, 0.25)
PARCHMENT = colors.Color(0.98, 0.965, 0.94)    # warm off-white background
CARD_BG = colors.Color(0.995, 0.99, 0.98)
RULE = colors.Color(0.85, 0.81, 0.72)          # light tan border

PAGE_MARGIN = 0.65 * inch

SECTIONS = [
    ("problem", "Problem"),
    ("method", "Method"),
    ("results", "Results"),
    ("limitations", "Limitations"),
    ("key_contributions", "Key Contributions"),
]

_styles = {
    "title": ParagraphStyle(
        "SummaryTitle", fontName="Helvetica-Bold", fontSize=17,
        textColor=colors.white, leading=21,
    ),
    "eyebrow": ParagraphStyle(
        "Eyebrow", fontName="Helvetica", fontSize=8, tracking=1,
        textColor=colors.Color(1, 1, 1, alpha=0.75), leading=10,
    ),
    "label": ParagraphStyle(
        "SectionLabel", fontName="Helvetica-Bold", fontSize=8.5,
        textColor=AMBER, leading=11, spaceAfter=4,
    ),
    "body": ParagraphStyle(
        "SectionBody", fontName="Helvetica", fontSize=10, textColor=INK,
        leading=14.5, alignment=TA_LEFT,
    ),
    "footer": ParagraphStyle(
        "Footer", fontName="Helvetica", fontSize=8, textColor=SLATE,
    ),
}


def _header_footer(canvas, doc, document_title):
    canvas.saveState()
    page_w, page_h = LETTER

    # Footer: page number + generated-by line, small and out of the way.
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(SLATE)
    canvas.drawString(PAGE_MARGIN, 0.45 * inch, "Generated by Paquito")
    canvas.drawRightString(
        page_w - PAGE_MARGIN, 0.45 * inch, f"Page {doc.page}"
    )
    canvas.setStrokeColor(RULE)
    canvas.setLineWidth(0.5)
    canvas.line(PAGE_MARGIN, 0.62 * inch, page_w - PAGE_MARGIN, 0.62 * inch)
    canvas.restoreState()


def build_summary_pdf(document_title, summary):
    """
    document_title: str
    summary: dict with keys problem/method/results/limitations/key_contributions
    Returns a BytesIO positioned at 0, ready for send_file.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=LETTER,
        leftMargin=PAGE_MARGIN,
        rightMargin=PAGE_MARGIN,
        topMargin=PAGE_MARGIN,
        bottomMargin=0.85 * inch,
        title=f"{document_title} — Summary",
    )

    story = []

    # --- header band (teal, full width, rounded look via a single-cell table) --
    header_table = Table(
        [[Paragraph("DOCUMENT SUMMARY", _styles["eyebrow"])],
         [Paragraph(document_title or "Untitled document", _styles["title"])]],
        colWidths=[doc.width],
    )
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), TEAL),
        ("LEFTPADDING", (0, 0), (-1, -1), 16),
        ("RIGHTPADDING", (0, 0), (-1, -1), 16),
        ("TOPPADDING", (0, 0), (-1, 0), 14),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 2),
        ("TOPPADDING", (0, 1), (-1, 1), 2),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 16),
        ("LINEBELOW", (0, -1), (-1, -1), 3, TEAL_DARK),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 22))

    generated_at = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    story.append(Paragraph(f"Generated {generated_at}", _styles["footer"]))
    story.append(Spacer(1, 14))

    # --- one bordered "card" per section, matching the app's tab-card look ---
    for key, label in SECTIONS:
        body_text = (summary.get(key) or "—").replace("\n", "<br/>")
        cell_content = [
            Paragraph(label.upper(), _styles["label"]),
            Paragraph(body_text, _styles["body"]),
        ]
        card = Table([[cell_content]], colWidths=[doc.width])
        card.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
            ("BOX", (0, 0), (-1, -1), 0.75, RULE),
            ("LEFTPADDING", (0, 0), (-1, -1), 14),
            ("RIGHTPADDING", (0, 0), (-1, -1), 14),
            ("TOPPADDING", (0, 0), (-1, -1), 12),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ]))
        story.append(card)
        story.append(Spacer(1, 10))

    doc.build(
        story,
        onFirstPage=lambda c, d: _header_footer(c, d, document_title),
        onLaterPages=lambda c, d: _header_footer(c, d, document_title),
    )
    buf.seek(0)
    return buf